apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fastiride
spec:
  selector:
    app: postgres
  clusterIP: None   # headless — StatefulSet pods get stable DNS: postgres-0.postgres
  ports:
    - port: 5432
      targetPort: 5432
