backend:
  replicas: 1
  irsa:
    roleArn: "arn:aws:iam::439594592108:role/fastiride-dev-backend-irsa"

frontend:
  replicas: 1

ingress:
  host: fastiride.app

config:
  googleRedirectUri: https://fastiride.app/api/auth/google/callback

hpa:
  enabled: false
