apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastiride-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lidormazor42/FastiRide
    targetRevision: main   # every merge to main updates staging's image tags (see CI)
    path: helm/fastiride
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastiride-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
