apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastiride-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/FastiRide
    targetRevision: main   # prod tracks only the stable main branch
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: fastiride-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
