apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastiride-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # cleans up K8s resources on app delete
spec:
  project: default
  source:
    repoURL: https://github.com/lidormazor42/FastiRide
    targetRevision: HEAD
    path: helm/fastiride
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fastiride-dev
  syncPolicy:
    automated:
      prune: true      # remove resources deleted from Git
      selfHeal: true   # revert manual kubectl changes
    syncOptions:
      - CreateNamespace=true
