apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fastiride.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsa.roleArn | quote }}
