"""add ride notes column

Revision ID: 21e6db21b130
Revises: 0ecc1049bafc
Create Date: 2026-07-21 14:08:44.163117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e6db21b130'
down_revision: Union[str, None] = '0ecc1049bafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'notes')
    # ### end Alembic commands ###
