"""drop ride notes column

Revision ID: 5b6c9805a455
Revises: 21e6db21b130
Create Date: 2026-07-21 14:17:26.600823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b6c9805a455'
down_revision: Union[str, None] = '21e6db21b130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
